controller_list:
  - name: fake_manipulator_controller
    joints:
      - swing_joint
      - boom_joint
      - arm_joint
      - bucket_joint
      - bucket_end_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home